const {series, parallel, watch, src, dest} = require('gulp');
const pump = require('pump');
const fs = require('fs');
const path = require('path');
const order = require('ordered-read-streams');

// gulp plugins and utils
const livereload = require('gulp-livereload');
const postcss = require('gulp-postcss');
const concat = require('gulp-concat');
const uglify = require('gulp-uglify');
const beeper = require('beeper');
const zip = require('gulp-zip');

// postcss plugins
const easyimport = require('postcss-easy-import');
const nested = require('postcss-nested');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');

// translations support
const { mergeLocales } = require('@tryghost/theme-translations/build');
const sharedThemeAssetsPath = path.dirname(require.resolve('@tryghost/shared-theme-assets/package.json'));

function serve(done) {
    livereload.listen();
    done();
}

function handleError(done) {
    return function (err) {
        if (err) {
            beeper();
        }
        return done(err);
    };
};

function hbs(done) {
    pump([
        src(['*.hbs', 'partials/**/*.hbs']),
        livereload()
    ], handleError(done));
}

function css(done) {
    pump([
        src('assets/css/screen.css', {sourcemaps: true}),
        postcss([
            easyimport,
            nested,
            autoprefixer(),
            cssnano()
        ]),
        dest('assets/built/', {sourcemaps: '.'}),
        livereload()
    ], handleError(done));
}

function getJsFiles(version) {
    const jsFiles = [
        src(`${sharedThemeAssetsPath}/assets/js/${version}/lib/**/*.js`),
        src(`${sharedThemeAssetsPath}/assets/js/${version}/main.js`),
    ];

    if (fs.existsSync(`assets/js/lib`)) {
        jsFiles.push(src(`assets/js/lib/*.js`));
    }

    jsFiles.push(src(`assets/js/main.js`));

    return jsFiles;
}

function js(done) {
    pump([
        order(getJsFiles('v1'), {sourcemaps: true}),
        concat('main.min.js'),
        uglify(),
        dest('assets/built/', {sourcemaps: '.'}),
        livereload()
    ], handleError(done));
}

function dataLoader(done) {
  pump(
    [
      // Cards render server-side now; assets/js/cards/ is progressive enhancement
      // only. data-loader.js stays for finance.hbs, which is still client-driven.
      order(
        [
          src("assets/js/data-loader.js", { sourcemaps: true }),
          src("assets/js/cards/*.js", { sourcemaps: true }),
        ],
        { sourcemaps: true }
      ),
      concat("data-loader.min.js"),
      uglify(),
      dest("assets/built/", { sourcemaps: "." }),
      livereload(),
    ],
    handleError(done)
  );
}

// Landing pages are templates, not posts, so the seeder cannot fill their pickers.
// Render them at build time into partials the templates include, keeping the option
// list server-side (crawlable, works with JS off) instead of fetched in the browser.
function cardPartials(done) {
  const { renderCard } = require("./scripts/cards");
  const outDir = "partials/generated";
  fs.mkdirSync(outDir, { recursive: true });

  const PICKERS = [
    ["offices", "Choose an office"],
    ["officials", "Choose an official"],
    ["elections", "Choose an election"],
    ["donors", "Choose a donor"],
    ["jurisdictions", "Choose a jurisdiction"],
  ];

  for (const [source, label] of PICKERS) {
    const html = renderCard("entity-picker", { source, label });
    fs.writeFileSync(
      `${outDir}/picker-${source}.hbs`,
      `{{!-- GENERATED by gulp cardPartials from @publicledger/data. Do not edit. --}}\n${html}\n`
    );
  }
  done();
}

// FORK CUSTOM: publish the data package to assets/built/data/ for the browser.
// The source is resolved by scripts/cards/data.js — the SAME resolver the card
// seeder uses — so the build and the seeded post bodies can never disagree about
// which data they read. Installing the real @publicledger/data package is all it
// takes to switch both over; nothing here names the mock.
function dataCopy(done) {
  const dataRoot = require("./scripts/cards/data").root();
  pump(
    [src(`${dataRoot}/**/*.json`, { encoding: false }), dest("assets/built/data/")],
    handleError(done)
  );
}

function zipper(done) {
    const filename = require('./package.json').name + '.zip';

    pump(
      [
        src(
          [
            "**",
            "!node_modules",
            "!node_modules/**",
            "!dist",
            "!dist/**",
            "!pnpm-debug.log",
            "!pnpm-lock.yaml",
            "!pnpm-workspace.yaml",
            "!AGENTS.md",
            "!CLAUDE.md",
            "!docs-local",
            "!docs-local/**",
            "!test",
            "!test/**",
            "!data",
            "!data/**",

            // FORK CUSTOM: the glob above is "**" with { dot: true }, so every
            // dotfile and dot-directory in the repo was being packaged and
            // uploaded to the production Ghost site. `.git` alone was 2.4 MB
            // across 229 entries -- about 65% of the artifact, and larger than
            // the theme itself. Ghost needs the templates, partials,
            // assets/built, assets/fonts, locales and package.json; nothing
            // below is read at render time.

            // Every dot-entry, at any depth. Ghost reads no dotfiles from a
            // theme, and enumerating them one by one is a denylist that always
            // lags: building from a working checkout (rather than a fresh CI
            // clone) also picked up `.env` -- the Ghost Admin API credentials
            // used by `pnpm ghost:seed` -- along with `.claude/`. Those are
            // gitignored, so they are invisible to any CI-only test. Excluding
            // the whole class is the only version that stays correct.
            "!**/.*",
            "!**/.*/**",

            // Build tooling that lives at the repo root
            "!eslint.config.js",
            "!gulpfile.js",

            // Scratch output (gulp intermediate, local experiments)
            "!tmp",
            "!tmp/**",

            // routes.yaml stays in the package on purpose. Ghost ignores it in
            // a theme, but nothing can deliver it to production automatically:
            // an integration's API key gets 403 on the routes endpoint, which
            // only accepts a logged-in staff user. Routes are applied by hand,
            // so shipping the file keeps the artifact self-describing.

            // Fork tooling and documentation. scripts/ is seed and card
            // tooling run against a local Ghost; the devcontainer bind-mounts
            // the repo itself, so excluding it here does not affect local dev.
            "!scripts",
            "!scripts/**",
            "!sync",
            "!sync/**",
            "!AGENT_LESSONS.md",
            "!AI_DEVELOPMENT.md",
            "!CONTRIBUTING.md",
            "!DEVCONTAINER.md",
            "!README.FORK.md",
            "!TROUBLESHOOTING.md",

            // Source CSS/JS -- PostCSS and the js task compile these into
            // assets/built, which is what the templates load via {{asset}}.
            // The only references to these paths in .hbs files are comments.
            "!assets/css",
            "!assets/css/**",
            "!assets/js",
            "!assets/js/**",

            // Explicitly include built assets (in .gitignore but needed in package)
            "assets/built/**",
          ],
          { encoding: false, dot: true }
        ),
        zip(filename),
        dest("dist/"),
      ],
      handleError(done)
    );
}

function locales(done) {
    mergeLocales({
        local: './locales-local',
        output: './locales'
    })(done);
}

const localesWatcher = () => watch('./locales-local/**/*.json', locales);
const hbsWatcher = () => watch(['*.hbs', 'partials/**/*.hbs'], hbs);
const cssWatcher = () => watch('assets/css/**/*.css', css);
const jsWatcher = () => watch('assets/js/**/*.js', js);
const dataLoaderWatcher = () =>
  watch(["assets/js/data-loader.js", "assets/js/cards/*.js"], dataLoader);
// FORK CUSTOM: only worth watching while the data lives in this repo. Once the real
// package is installed the files sit in node_modules and change only on reinstall,
// so watching them would cost a large recursive watch for nothing.
const dataWatcher = () => {
  const data = require("./scripts/cards/data");
  if (!data.rootIsLocal()) return Promise.resolve();
  return watch(`${data.root()}/**/*.json`, series(cardPartials, dataCopy));
};
const watcher = parallel(
  hbsWatcher,
  cssWatcher,
  jsWatcher,
  dataLoaderWatcher,
  dataWatcher,
  localesWatcher
);
const build = series(css, js, dataLoader, cardPartials, dataCopy, locales);

exports.cardPartials = cardPartials;
exports.build = build;
exports.zip = series(build, zipper);
exports.default = series(build, serve, watcher);
