const {series, parallel, watch, src, dest} = require('gulp');
const pump = require('pump');
const fs = require('fs');
const path = require('path');
const order = require('ordered-read-streams');

// gulp plugins and utils
const livereload = require('gulp-livereload');
const postcss = require('gulp-postcss');
const concat = require('gulp-concat');
const uglify = require('gulp-uglify');
const beeper = require('beeper');
const zip = require('gulp-zip');

// postcss plugins
const easyimport = require('postcss-easy-import');
const nested = require('postcss-nested');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');

// translations support
const { mergeLocales } = require('@tryghost/theme-translations/build');
const sharedThemeAssetsPath = path.dirname(require.resolve('@tryghost/shared-theme-assets/package.json'));

function serve(done) {
    livereload.listen();
    done();
}

function handleError(done) {
    return function (err) {
        if (err) {
            beeper();
        }
        return done(err);
    };
};

function hbs(done) {
    pump([
        src(['*.hbs', 'partials/**/*.hbs']),
        livereload()
    ], handleError(done));
}

function css(done) {
    pump([
        src('assets/css/screen.css', {sourcemaps: true}),
        postcss([
            easyimport,
            nested,
            autoprefixer(),
            cssnano()
        ]),
        dest('assets/built/', {sourcemaps: '.'}),
        livereload()
    ], handleError(done));
}

function getJsFiles(version) {
    const jsFiles = [
        src(`${sharedThemeAssetsPath}/assets/js/${version}/lib/**/*.js`),
        src(`${sharedThemeAssetsPath}/assets/js/${version}/main.js`),
    ];

    if (fs.existsSync(`assets/js/lib`)) {
        jsFiles.push(src(`assets/js/lib/*.js`));
    }

    jsFiles.push(src(`assets/js/main.js`));

    return jsFiles;
}

function js(done) {
    pump([
        order(getJsFiles('v1'), {sourcemaps: true}),
        concat('main.min.js'),
        uglify(),
        dest('assets/built/', {sourcemaps: '.'}),
        livereload()
    ], handleError(done));
}

function dataLoader(done) {
  pump(
    [
      // Cards render server-side now; assets/js/cards/ is progressive enhancement
      // only. data-loader.js stays for finance.hbs, which is still client-driven.
      order(
        [
          src("assets/js/data-loader.js", { sourcemaps: true }),
          src("assets/js/cards/*.js", { sourcemaps: true }),
        ],
        { sourcemaps: true }
      ),
      concat("data-loader.min.js"),
      uglify(),
      dest("assets/built/", { sourcemaps: "." }),
      livereload(),
    ],
    handleError(done)
  );
}

// Landing pages are templates, not posts, so the seeder cannot fill their pickers.
// Render them at build time into partials the templates include, keeping the option
// list server-side (crawlable, works with JS off) instead of fetched in the browser.
function cardPartials(done) {
  const { renderCard } = require("./scripts/cards");
  const outDir = "partials/generated";
  fs.mkdirSync(outDir, { recursive: true });

  const PICKERS = [
    ["offices", "Choose an office"],
    ["officials", "Choose an official"],
    ["elections", "Choose an election"],
    ["donors", "Choose a donor"],
    ["jurisdictions", "Choose a jurisdiction"],
  ];

  for (const [source, label] of PICKERS) {
    const html = renderCard("entity-picker", { source, label });
    fs.writeFileSync(
      `${outDir}/picker-${source}.hbs`,
      `{{!-- GENERATED by gulp cardPartials from @publicledger/data. Do not edit. --}}\n${html}\n`
    );
  }
  done();
}

function dataCopy(done) {
  // Use mock @publicledger/data package for development
  // In production, this will come from the real NPM package
  const mockPackagePath = "test/mocks/publicledger-data/data";
  const dataSource = fs.existsSync(mockPackagePath)
    ? `${mockPackagePath}/**/*.json`
    : "data/**/*.json"; // Fallback if real package is installed

  pump([src(dataSource, { encoding: false }), dest("assets/built/data/")], handleError(done));
}

function zipper(done) {
    const filename = require('./package.json').name + '.zip';

    pump(
      [
        src(
          [
            "**",
            "!node_modules",
            "!node_modules/**",
            "!dist",
            "!dist/**",
            "!pnpm-debug.log",
            "!pnpm-lock.yaml",
            "!pnpm-workspace.yaml",
            "!AGENTS.md",
            "!CLAUDE.md",
            "!docs-local",
            "!docs-local/**",
            "!test",
            "!test/**",
            "!data",
            "!data/**",
            // Explicitly include built assets (in .gitignore but needed in package)
            "assets/built/**",
          ],
          { encoding: false, dot: true }
        ),
        zip(filename),
        dest("dist/"),
      ],
      handleError(done)
    );
}

function locales(done) {
    mergeLocales({
        local: './locales-local',
        output: './locales'
    })(done);
}

const localesWatcher = () => watch('./locales-local/**/*.json', locales);
const hbsWatcher = () => watch(['*.hbs', 'partials/**/*.hbs'], hbs);
const cssWatcher = () => watch('assets/css/**/*.css', css);
const jsWatcher = () => watch('assets/js/**/*.js', js);
const dataLoaderWatcher = () =>
  watch(["assets/js/data-loader.js", "assets/js/cards/*.js"], dataLoader);
const dataWatcher = () =>
  watch("test/mocks/publicledger-data/data/**/*.json", series(cardPartials, dataCopy));
const watcher = parallel(
  hbsWatcher,
  cssWatcher,
  jsWatcher,
  dataLoaderWatcher,
  dataWatcher,
  localesWatcher
);
const build = series(css, js, dataLoader, cardPartials, dataCopy, locales);

exports.cardPartials = cardPartials;
exports.build = build;
exports.zip = series(build, zipper);
exports.default = series(build, serve, watcher);
